name: After Test

on: 
  workflow_run:
    workflows:
      - Test
    types:
      - completed
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: echo "::debug::Set the Octocat variable"
