name: Release

on:
  push:
    branches:
      - action-merge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Release
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          lein release :patch

