name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - action-merge
  # push:
  #   branches:
  #     - action-merge

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_SECRET_KEY }} 

        # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          lein release :patch


