name: Release

on:
  push:
    branches:
      - action-merge

jobs:
  release:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-contexts
      - name: Release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          lein release :patch

