name: Release

on:
  push:
    branches:
      - action-merge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_SECRET_KEY }} 

        # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-contexts
      - name: Release
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
        run: |
          # git config user.name github-actions
          # git config user.email github-actions@github.com
          git config user.name deadghost-bot
          git config user.email kliu@symplr.com
          lein release :patch

