name: Test

on: push
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: lein deps
  # test:
  #   runs-on: ubuntu-latest
  #   needs: deps
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Run tests
  #     run: lein test
