name: Test

on:
  workflow_run:
    workflows: ["Deps"]
    types: [completed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: lein test
